#!/bin/bash
while read -r line
do
  echo "ping $line"
  if ping -c 1 $line &> /dev/null
then
  echo "running $line"
    sshpass -p Start#@1 ssh-copy-id e.kandaurov@$line -o "StrictHostKeyChecking no"
else
  echo "$line недоступен"
fi
done < "server.list"



#####
в server server.list вписываем адреса хостов

##################### Реализовать обмен ключами SSH

[root@Ansible ~]# ssh-keygen
Generating public/private rsa key pair.
Enter file in which to save the key (/root/.ssh/id_rsa):
Created directory '/root/.ssh'.
Enter passphrase (empty for no passphrase):
Enter same passphrase again:
Your identification has been saved in /root/.ssh/id_rsa.
Your public key has been saved in /root/.ssh/id_rsa.pub.
The key fingerprint is:
ad:c8:99:6b:70:b2:c0:10:2e:4b:c7:68:52:2d:17:e0 root@John
The key's randomart image is:
+--[ RSA 2048]----+
|  .o..           |
|..o o            |
|.oEo             |
|+= o     .       |
|=+.     S .      |
|. o o..+ .       |
|   . == .        |
|    . ..         |
|     ..          |
+-----------------+
[root@Ansible ~]# chmod 700 /root/.ssh
[root@Ansible ~]# cat /root/.ssh/id_rsa.pub > /root/.ssh/authorized_keys
[root@Ansible ~]# chmod 600 /root/.ssh/authorized_keys
 # Синхронизация с другими машинами
[root@Ansible ~]# scp .ssh/authorized_keys root@192.168.102.133:/root/.ssh/
[root@Ansible ~]# ssh 192.168.102.133


######################параметры подключения ssh:

ansible_ssh_host

Имя удаленного хоста, который нужно подключить. Если он отличается от псевдонима хоста, который вы хотите установить, его можно установить с помощью этой переменной.


ansible_ssh_port

номер порта ssh. Если это не номер порта по умолчанию, установите эту переменную.


ansible_ssh_user

Имя пользователя ssh по умолчанию


ansible_ssh_pass

пароль ssh (этот метод небезопасен, мы настоятельно рекомендуем использовать ключ --ask-pass или SSH)


ansible_ssh_private_key_file

Файл закрытого ключа, используемый ssh. Он применим, когда у вас есть несколько ключей, и вы не хотите использовать агент SSH.


ansible_ssh_common_args

Этот параметр добавляется к командной строке по умолчанию sftp, scp и ssh


ansible_sftp_extra_args

Этот параметр добавляется к командной строке sftp по умолчанию.


ansible_scp_extra_args

Этот параметр добавляется к командной строке scp по умолчанию.


ansible_ssh_extra_args

Этот параметр добавляется к командной строке ssh по умолчанию.


ansible_ssh_pipelining

Определите, следует ли использовать канал SSH. Это может переопределить настройки в
ansible.cfg.
